# Generated by Django 4.0.3 on 2022-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1234, upload_to='images'),
            preserve_default=False,
        ),
    ]
